# Generated by Django 4.0.6 on 2022-07-08 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_number', to='bag.bag')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending...', 'Pending...'), ('Order Confirmed', 'Order Confirmed'), ('Lovingly Being Made...', 'Lovingly Being Made...'), ('A Masterpiece is born!', 'A Masterpiece is born!'), ('On its way to its new home!', 'On its way to its new home!'), ('Successfully Delivered!', 'Successfully Delivered!')], default='Pending...', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='bag.order')),
            ],
        ),
    ]
