# Generated by Django 4.0.6 on 2022-07-09 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('back_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back', to='products.product')),
                ('bottom_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottom', to='products.product')),
                ('clasp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasp', to='products.product')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag', to=settings.AUTH_USER_MODEL)),
                ('front_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front', to='products.product')),
                ('heart_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heart', to='products.product')),
                ('lining_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lining', to='products.product')),
                ('pocket_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pocket', to='products.product')),
                ('strap_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strap', to='products.product')),
                ('top_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top', to='products.product')),
                ('zip_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zip', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_number', to='bag.bag')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending...', 'Pending...'), ('Order Confirmed', 'Order Confirmed'), ('Lovingly Being Made...', 'Lovingly Being Made...'), ('A Masterpiece is born!', 'A Masterpiece is born!'), ('On its way to its new home!', 'On its way to its new home!'), ('Successfully Delivered!', 'Successfully Delivered!')], default='Pending...', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='bag.order')),
            ],
        ),
    ]
