# Generated by Django 4.0.6 on 2022-07-08 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('bag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bag',
            name='back_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back', to='products.product'),
        ),
        migrations.AddField(
            model_name='bag',
            name='bottom_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottom', to='products.product'),
        ),
        migrations.AddField(
            model_name='bag',
            name='clasp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasp', to='products.product'),
        ),
        migrations.AddField(
            model_name='bag',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bag',
            name='front_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front', to='products.product'),
        ),
        migrations.AddField(
            model_name='bag',
            name='heart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heart', to='products.product'),
        ),
        migrations.AddField(
            model_name='bag',
            name='lining_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lining', to='products.product'),
        ),
        migrations.AddField(
            model_name='bag',
            name='pocket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pocket', to='products.product'),
        ),
        migrations.AddField(
            model_name='bag',
            name='strap_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strap', to='products.product'),
        ),
        migrations.AddField(
            model_name='bag',
            name='top_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top', to='products.product'),
        ),
        migrations.AddField(
            model_name='bag',
            name='zip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zip', to='products.product'),
        ),
    ]
