# Generated by Django 4.0.6 on 2022-07-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0004_alter_orderstatus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='bag',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
            preserve_default=False,
        ),
    ]
