# Generated by Django 4.0.6 on 2022-07-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0005_rename_price_order_total_price_bag_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bag_id',
        ),
    ]
