# Generated by Django 4.0.6 on 2022-07-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0007_bag_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
