# Generated by Django 4.0.6 on 2022-08-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0009_order_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='back_id',
            new_name='back',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='bottom_id',
            new_name='bottom',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='clasp_id',
            new_name='clasp',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='front_id',
            new_name='front',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='heart_id',
            new_name='heart',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='lining_id',
            new_name='lining',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='pocket_id',
            new_name='pocket',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='side_strap_id',
            new_name='side_strap',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='strap_id',
            new_name='strap',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='top_id',
            new_name='top',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='zip_id',
            new_name='zip',
        ),
        migrations.AlterField(
            model_name='bag',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bag.order'),
        ),
    ]
