# Generated by Django 4.0.6 on 2022-08-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0010_rename_back_id_bag_back_rename_bottom_id_bag_bottom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='back',
        ),
    ]
