# Generated by Django 4.0.6 on 2022-08-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_part'),
        ('bag', '0011_remove_bag_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='clasp',
        ),
        migrations.AddField(
            model_name='bag',
            name='clasps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasps', to='products.product'),
        ),
    ]
