# Generated by Django 4.0.6 on 2022-07-09 16:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part', models.CharField(choices=[('Blank', 'Blank'), ('Front', 'Front'), ('Back', 'Back'), ('Top', 'Top'), ('Bottom', 'Bottom'), ('Strap', 'Strap'), ('Lining', 'Lining'), ('Zip', 'Zip'), ('Heart', 'Heart'), ('Pocket', 'Pocket'), ('Clasps', 'Clasps')], default='Blank', max_length=20)),
                ('image', models.CharField(max_length=200, null=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.fabric')),
            ],
        ),
    ]
