# Generated by Django 4.0.6 on 2022-07-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part',
            field=models.CharField(choices=[('Blank', 'Blank'), ('Front', 'Front'), ('Back', 'Back'), ('Top', 'Top'), ('Bottom', 'Bottom'), ('Strap', 'Strap'), ('Lining', 'Lining'), ('Zip', 'Zip'), ('Heart', 'Heart'), ('Pocket', 'Pocket'), ('Clasps', 'Clasps'), ('Side strap', 'Side strap')], default='Blank', max_length=20),
        ),
    ]
