# Generated by Django 4.0.6 on 2022-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part',
            field=models.CharField(choices=[('blank', 'blank'), ('front', 'front'), ('back', 'back'), ('top', 'top'), ('bottom', 'bottom'), ('strap', 'strap'), ('lining', 'lining'), ('zip', 'zip'), ('heart', 'heart'), ('pocket', 'pocket'), ('clasps', 'clasps'), ('side_strap', 'side_strap')], default='blank', max_length=20),
        ),
    ]
